# -*- coding: utf-8 -*-
"""Indian Cinema Theatres.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15Z3ZikakUoFU7Rs8Zvg4kmjgMk-7RzeV

Indian Cinema Theatres - Python Analysis
"""

# Commented out IPython magic to ensure Python compatibility.
import numpy as np
import pandas as pd
from collections import defaultdict
import folium
import seaborn as sns
import plotly.express as px
import matplotlib.pyplot as plt
# %matplotlib inline

df=pd.read_csv('/content/indian-movie-theatres.csv')

display(df.sample(5))

df.shape

df.columns

df.info()

df.isna().sum()

"""Dealing with Null Values"""

nans = df.isna().sum()
ft = list(nans.index)
values = list(nans.values)

plt.figure(figsize=(15,8))
sns.set(style='whitegrid',color_codes=True)
sns.barplot(x=ft,y=values)
plt.xticks(rotation=90)
plt.axhline(y=289,linewidth=1,color='r')
plt.show()

df['City Name'].unique()

df.isna().sum()

df.drop('Theatre Chain',axis=1,inplace=True)

plt.figure(figsize=(15,5))
sns.heatmap(df.select_dtypes(include=np.number).corr(), annot=True)
plt.show()

df['Screens'].value_counts()

df.isna().sum()

num_features = ['Calculated Seats', 'Number of Screens']

for i in num_features:
    sns.lmplot(x=i, y='Ticket Prices', data=df)

df['City Name'].unique()

df['City Name'].value_counts()

sns.set(rc = {'figure.figsize':(20,10)})
sns.boxplot(x='City Name', y='Ticket Prices', data=df)

df['Type'].replace({'Single Screen':0, 'Multiplex':1}, inplace = True)

sns.set_style('whitegrid')
plot=sns.lmplot(x ='Type', y ='Ticket Prices', data = df,col='City Name', hue ='City Name',height=5,col_wrap=5)









